"""empty message

Revision ID: 1ecfa7847d7a
Revises: 
Create Date: 2024-01-21 15:39:53.640034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ecfa7847d7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('author')
    op.drop_table('book')
    op.drop_table('publisher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('publisher_name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('book_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('publisher_id', sa.INTEGER(), nullable=True),
    sa.Column('author_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('publisher_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('publication_date', sa.VARCHAR(length=255), nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
